import Layout from "@/components/layout/layout";
import { ClientContextProvider } from "@/context/clients/client";
import AuthGuard from "@/hooks/guard/auth.guard";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientContextProvider>
          <AuthGuard>
            <Layout>{children}</Layout>
          </AuthGuard>
        </ClientContextProvider>
      </body>
    </html>
  );
}
